convtasnet:
  frame_length: 256
  frame_step: 128
  hop_length: 256
  input_channels: 2
  n_fft: 512
  num_repeats: 5
  num_sources: 2
data:
  music_tracks_file: /mnt/scratch/sc22ol/metadata
  root_path: /mnt/scratch/sc22ol/audio
  sample_rate: 44100
  samples_per_track: 8
  segment_length: 3.0
  target: Bassoon
main_args:
  exp_dir: exp/tmp
  help: null
optim:
  lr: 0.0001
positional arguments: {}
training:
  aggregate: 1
  batch_size: 4
  early_stop: true
  epochs: 200
  half_lr: true
  num_workers: 4
