convtasnet:
  B: 256
  C: 2
  H: 512
  L: 20
  N: 256
  P: 3
  R: 4
  X: 10
  audio_channels: 2
  causal: false
  mask_nonlinear: relu
  norm_type: gLN
data:
  music_tracks_file: /nobackup/sc22ol/metadata
  root_path: /nobackup/sc22ol/audio
  sample_rate: 44100
  samples_per_track: 64
  segment_length: 3.0
  target: Bassoon
main_args:
  exp_dir: exp/tmp
  help: null
optim:
  lr: 0.0001
positional arguments: {}
training:
  aggregate: 1
  batch_size: 4
  early_stop: true
  epochs: 200
  half_lr: true
  num_workers: 4
