convtasnet:
  frame_length: 256
  frame_step: 128
  hop_length: 350
  input_channels: 2
  n_fft: 512
  num_repeats: 5
  num_sources: 2
data:
  root_path: /mnt/scratch/sc22ol/eval_set/cadenza_cad2_task2_eval.v1_1/cadenza_data/cad2/task2/audio/
  music_tracks_file: /mnt/scratch/sc22ol/eval_set/cadenza_cad2_task2_eval.v1_1/cadenza_data/cad2/task2/metadata/
  sample_rate: 44100
  samples_per_track: 64
  segment_length: 3.0
  target: Violin
main_args:
  exp_dir: crm50/Violin
  help: null
optim:
  lr: 0.0005
positional arguments: {}
training:
  aggregate: 1
  batch_size: 4
  early_stop: true
  epochs: 50
  half_lr: true
  num_workers: 4
