# ConvTasNet config
convtasnet:
  n_fft: 512
  hop_length: 256
  input_channels: 2
  frame_length: 64
  frame_step: 32

# Training config
training:
  epochs: 200
  batch_size: 4
  num_workers: 4
  half_lr: yes
  early_stop: yes
  aggregate: 1
# Optim config
optim:
  lr: 0.0001
# Data config
data:
  root_path: /mnt/scratch/sc22ol/audio
  music_tracks_file: /mnt/scratch/sc22ol/metadata
  sample_rate: 44100
  target: 'Bassoon'
  samples_per_track: 8
  segment_length: 3.0


