# ConvTasNet config
convtasnet:
  frame_length: 256
  frame_step: 128
  hop_length: 350
  input_channels: 2
  n_fft: 512
  num_repeats: 5
  num_sources: 2

# Training config
training:
  epochs: 50
  batch_size: 4
  num_workers: 4
  half_lr: yes
  early_stop: yes
  aggregate: 1
# Optim config
optim:
  lr: 0.0001
# Data config
data:
  root_path: /mnt/scratch/sc22ol/audio
  music_tracks_file: /mnt/scratch/sc22ol/metadata
  sample_rate: 44100
  target: 'Clarinet'
  samples_per_track: 64
  segment_length: 3.0

